# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rspec", "~> 3.6"
gem "coderay", "~> 1.1"
# gem "httparty", "~> 0.21.0"
